package protocol

// Client message types
const (
	MsgTypeJoin          = "join"
	MsgTypeStartGame     = "start_game"
	MsgTypeChat          = "chat"
	MsgTypeMove          = "move"
	MsgTypeExamine       = "examine"
	MsgTypeDo            = "do"
	MsgTypeTalk          = "talk"
	MsgTypeGive          = "give"
	MsgTypeUse           = "use"
	MsgTypeVote          = "vote"
	MsgTypeSolveAnswer   = "solve_answer"
	MsgTypeEndProposal   = "end_proposal"
	MsgTypeEndVote       = "end_vote"
	MsgTypeInventory     = "inventory"
	MsgTypeRoleInfo      = "role_info"
	MsgTypeMapInfo       = "map_info"
	MsgTypeWhoInfo       = "who_info"
	MsgTypeHelp          = "help"
	MsgTypeFeedback      = "feedback"
	MsgTypeReady         = "ready"
	MsgTypeThemeKeyword  = "theme_keyword"
)

// Server message types
const (
	SMsgTypeJoined              = "joined"
	SMsgTypeLobbyUpdate         = "lobby_update"
	SMsgTypeGenerationProgress  = "generation_progress"
	SMsgTypeError               = "error"
	SMsgTypePlayerDisconnected  = "player_disconnected"
	SMsgTypePlayerReconnected   = "player_reconnected"
	SMsgTypeBriefingPublic      = "briefing_public"
	SMsgTypeBriefingPrivate     = "briefing_private"
	SMsgTypeGameStarted         = "game_started"
	SMsgTypeChat                = "chat"
	SMsgTypeGameEvent           = "game_event"
	SMsgTypeRoomChanged         = "room_changed"
	SMsgTypePlayerJoinedRoom    = "player_joined_room"
	SMsgTypePlayerLeftRoom      = "player_left_room"
	SMsgTypeSystem              = "system"
	SMsgTypeInventory           = "inventory"
	SMsgTypeRoleInfo             = "role_info"
	SMsgTypeMapInfo             = "map_info"
	SMsgTypeWhoInfo             = "who_info"
	SMsgTypeHelp                = "help"
	SMsgTypeVoteStarted         = "vote_started"
	SMsgTypeVoteProgress        = "vote_progress"
	SMsgTypeVoteEnded           = "vote_ended"
	SMsgTypeEndProposed         = "end_proposed"
	SMsgTypeEndVoteResult       = "end_vote_result"
	SMsgTypeSolveStarted        = "solve_started"
	SMsgTypeSolveProgress       = "solve_progress"
	SMsgTypeSolveResult         = "solve_result"
	SMsgTypeGameEnding          = "game_ending"
	SMsgTypeFeedbackRequest     = "feedback_request"
	SMsgTypeFeedbackAck         = "feedback_ack"
	SMsgTypeGameCancelled       = "game_cancelled"
	SMsgTypeGameFinished        = "game_finished"
	SMsgTypeThinking            = "thinking"
)
